name: todo_app_playground_4_bloc_two_ss
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  bloc_concurrency: ^0.3.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_hooks: ^0.21.2
  flutter_slidable: ^4.0.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
